# This configuration creates a Kubernetes cluster with 1 control-plane node and 3 worker nodes
# using Kind (Kubernetes IN Docker) for local development and testing
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker